language: node_js
node_js:
  - "8.12.0"
dist: trusty
sudo: required

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - npm run build_lib
  - ng build --prod --base-href ./
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/ngx-scrollbar-indicator-app
  on:
    branch: master
