language: node_js
node_js:
  - "10.14.2"
dist: trusty
sudo: required

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
- node_modules

branches:
  only:
  - master

before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g @angular/cli@7.0.2

script:
  - ng lint
  - ng test --watch=false
  - ng e2e
  - npm run build_lib
  - ng build --prod --base-href ./

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/ngx-scrollbar-indicator-app
  on:
    branch: master
