language: node_js
node_js:
  - "8.12.0"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run build --prod --base-href https://shhdharmen.github.io/ngx-scrollbar-indicator-app/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/ngx-scrollbar-indicator-app
  on:
    branch: master
