dist: trusty
sudo: required

language: node_js
node_js:
  - "10.14.2"

cache:
  directories:
     - ./node_modules

branches:
  only:
  - master

install:
  - npm install

script:
  - npm run lint
  - npm run test -- ngx-scrollbar-indicator --watch=false --progress=false --browsers=ChromeHeadlessCI
  # - npm run e2e -- --protractor-config=./e2e/protractor-ci.conf.js
  - npm run codecov
  - npm run build_lib
  - npm run build -- --prod --base-href /ngx-scrollbar-indicator/
  - mv dist/ngx-scrollbar-indicator-app/index.html dist/ngx-scrollbar-indicator-app/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/ngx-scrollbar-indicator-app
  on:
    branch: master
