language: node_js
node_js:
  - "10.14.2"
dist: trusty
sudo: required

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli
  - npm install codecov -g

script:
  - ng lint
  - npm run build_lib
  - ng build --prod --base-href ./

after_success:
  - codecov

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/ngx-scrollbar-indicator-app
  on:
    branch: master
