language: node_js
node_js:
  - "8.12.0"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm lint
  - npm build --base-href https://shhdharmen.github.io/ngx-scrollbar-indicator/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 281cd907d438fe2314ccd23161d954601c355c41
  local_dir: ngx-scrollbar-indicator
  on:
    branch: master